#!/bin/sh -e

sess=$(tmux list-sessions | head -n 1 | awk '{print $2}')

if [ ! -f /dev/shm/tmux${sess}.spc ] ; then 
    add=1
else 
    add=$(cat /dev/shm/tmux${sess}.spc)
fi

symbol="-"
if [ $add -eq 1 ] ; then
    symbol="+"
fi

echo "#[default]#[fg=colour13,bold,bg=$BYOBU_DARK]${symbol}#[default]#[fg=$BYOBU_LIGHT]#[bg=$BYOBU_DARK]"
