#!/bin/bash

git() { $HOME/bin/git "$@"; }

if [[ $# -lt 1 ]] ; then
    echo "Error, missing arg(s) ..."
    exit 1
fi

ag_args="-U --hidden"

gdir=$(git rev-parse --show-superproject-working-tree 2> /dev/null)
if [[ -z "$gdir" ]] ; then
    # not in a submodule, returns git root
    gdir=$(git rev-parse --show-toplevel 2> /dev/null)
fi

if [[ -z "$gdir" ]] ; then
    command ag $ag_args $@
    exit $?
fi

lastarg=${@:$#} # last parameter 
alloarg=${*%${!#}} # all parameters except the last

#echo "git dir: $gdir"
command ag $ag_args $@ $gdir
exit $?
