#!/bin/bash 

bfolder="pCloudDrive/hal9009"

cd ~
for d in \
bin dotfiles savesrcs addr_cleaner pargdb
do
  echo "d = $d"
  rsync -v -a --max-size=50M ~/$d ~/${bfolder} --delete
done

list_repo_info

# ppas ...
grep -r --include '*.list' '^deb ' /etc/apt/ | sed -re 's/^\/etc\/apt\/sources\.list((\.d\/)?|(:)?)//' -e 's/(.*\.list):/\[\1\] /' -e 's/deb http:\/\/ppa.launchpad.net\/(.*?)\/ubuntu .*/ppa:\1/' > ~/misc/ppa.list

cp -p ~/Downloads/repo_info.lst ~/misc
dpkg -l > ~/misc/dpkg.list
apt list --installed > ~/misc/apt.list

# dont use -a for misc - keep older stuff around
rsync -v -u -r --max-size=50M ~/misc ~/${bfolder}

rsync -v -a --max-size=50M --exclude 'google-chrome' --exclude 'Code' --exclude 'Microsoft' --exclude 'teams-insiders' --exclude 'libreoffice' ~/.config ~/${bfolder}/home --delete

rsync -v -a ~/radssh --exclude 'sessions' ~/${bfolder}/home --delete
rsync -v -a ~/.byobu   ~/${bfolder}/home --delete
rsync -v -a ~/.vim     ~/${bfolder}/home --delete
rsync -v -a ~/.nixnote ~/${bfolder}/home --delete

rsync -v -a ~/.local   ~/${bfolder}/home --exclude '.local/share/parcellite/*' --exclude '.local/share/zeitgeist/*' --exclude '.local/share/keyrings/*' --exclude '.local/share/applications/chrome-*.desktop' --exclude '.local/lib/*' --delete
#sync -v -a ~/.fzf   ~/${bfolder}/home --delete

rsync -v -u ~/.[a-z]* --exclude '.histfile' --exclude '.viminfo' --exclude '.localvimrc_persistent' --exclude '.zcompdump' --exclude '.zsh_history' --exclude '.bash_history' --exclude '.gksu.lock' --exclude '.radssh_history' --exclude '.python_history' --exclude '.sudo_as_admin_successful' --exclude '.lesshst' --exclude '.xsession-errors*' --exclude '.pcloud' ~/${bfolder}/home

rsync -v -a ~/Downloads/vim_bundles      ~/${bfolder}/Downloads --delete

rsync -v -u ~/Downloads/repo_info.lst ~/${bfolder}/Downloads
ls -ltr ~/Downloads > ~/${bfolder}/Downloads/ls-list.txt

