#!/bin/bash

if command -v batcat > /dev/null; then
  BATNAME="batcat"
else
  BATNAME="bat"
fi

bat=$(which $BATNAME 2> /dev/null)
if [[ -n "$bat" ]] ; then
    exec $BATNAME -A --plain --paging=never $@
fi
exec cat $@
