#!/bin/bash

cd ~/Downloads
for d in parcellite FlameGraph byobu perf-tools xsel tmux vim rtags cgdb ccache kitty terminator alacritty zsh-autosuggestions
do
    echo "checking $d ..."
    cd $d
    rc=$?
    if [[ $rc -eq 0 ]] ; then
        git remote -v
        git pull
        git smu
        cd ..
        echo " --- "
        echo ""
    fi
done

echo "checking ~/.fzf ..."
cd ~/.fzf
rc=$?
if [[ $rc -eq 0 ]] ; then
    git remote -v
    git pull
    git smu
    echo " --- "
    echo ""
fi

cd ~/Downloads/vim_bundles
./update.sh

echo ""
echo "Also check git:     ack, ag, fd, zsh, byobu, CopyQ, rxvt-unicode, CMake ..."
echo "Also check non-git: gcc/g++, clang/clang++/llvm, gdb, readline, ncurses ..."
echo ""
