#!/bin/bash

cd ~/Downloads
for d in parcellite xclip FlameGraph ethq byobu perf-tools xsel tmux vim rtags cgdb ccache
do
    echo "checking $d ..."
    cd $d
    rc=$?
    if [[ $rc -eq 0 ]] ; then
        git remote -v
        git pull
        git smu
        cd ..
        echo " --- "
        echo ""
    fi
done
cd vim_bundles
./update.sh

echo ""
echo "Also check git:     zsh, zsh-autosuggestions ..."
echo "Also check non-git: readline, gdb, ncurses ..."
echo ""
