#!/bin/bash

if [[ $# -ge 1 ]] ; then
    if [[ $1 == "-" ]] ; then
        exec copyq >/dev/null 2>/dev/null copy -
    else
        escapedtext=$(printf %q "$@")
        exec copyq >/dev/null 2>/dev/null copy $escapedtext
    fi

else
    exec copyq >/dev/null 2>/dev/null copy -
fi
