#!/usr/bin/python

# assuming there is a compile_commands.json file present -
# compdb -p . list > co.json
# mv co.json compile_commands.json
# rc -J .

# -*- coding: utf-8 -*-
import re
import sys

from compdb.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
