#!/bin/bash

# this is a script saved in a global path, such as /usr/local/bin/cycle_wins
# with a gnome hot-key mapping, such as Ctrl-Alt-q ...

set -e

export GITER=0

JS="""
const GLib = imports.gi.GLib;
const Clutter = imports.gi.Clutter;
const Meta = imports.gi.Meta;

var BreakException = {};

var eiter = GLib.getenv('GITER');
if (eiter == '' || eiter == 'NaN') {
    eiter = '0';
    GLib.setenv('GITER', eiter, true);
}

var giter;
var gmax = 0;

try {

gmax = 0;

global.get_window_actors().forEach(function (w) {
    var mw = w.meta_window;
    var wtitle = mw.get_wm_class();
    if (wtitle != 'Nautilus' && wtitle != 'Gnome-shell' && wtitle != '') {
        if (!mw.has_focus()) {
            gmax = gmax + 1;
        }
    }
});

global.get_window_actors().forEach(function (w) {
    var mw = w.meta_window;

    // var wtitle = mw.get_title();
    var wtitle = mw.get_wm_class();

    // global.log('1title: ', wtitle);

    if (wtitle != '' && wtitle != 'Nautilus' && wtitle != 'Gnome-shell' && (!wtitle.toLowerCase().includes('copyq'))) {

        if (mw.has_focus()) {

            // global.log('has_focus: ', wtitle);

        } else {

            // global.log('2title: ', wtitle);

            eiter = GLib.getenv('GITER');
            if (eiter == '' || eiter == 'NaN') {
                eiter = '0';
            }

            giter = parseInt(eiter, 10);

            if (giter >= gmax) {
                giter = 0;
            }

            // global.log('cxwins: giter', giter);
            // global.log('cxwins: eiter', eiter);
            // global.log('cxwins: gmax', gmax);

            if (giter == 0) {
                mw.activate(0);
                GLib.usleep(100000);

                // global.log('cxwins: pos 1');

                const [x, y] = global.get_pointer();
                const rect = new Meta.Rectangle({ x, y, width: 1, height: 1 });

                if ( ! rect.intersect(mw.get_frame_rect())[0] ) {
                    // pointer is not inside newly focused window, move it to window center ...
                    // global.log('cxwins: pos 2');
                    const rect1 = mw.get_frame_rect();
                    const x1 = rect1.x + rect1.width / 2;
                    const y1 = rect1.y + rect1.height / 2;
                    const seat = Clutter.get_default_backend().get_default_seat();
                    seat.warp_pointer(x1, y1);
                    // //const vdevice = seat.create_virtual_device( Clutter.InputDeviceType.POINTER_DEVICE );
                    // //vdevice.notify_absolute_motion(global.get_current_time()+5, x1, y1);
                    // global.log('cxwins: pos 2a');
                } else {
                    // pointer is already inside newly focused window, should we still move it ?
                    // global.log('cxwins: pos 3');
                    // const rect1 = mw.get_frame_rect();
                    // const x1 = rect1.x + rect1.width / 2;
                    // const y1 = rect1.y + rect1.height / 2;
                    // const seat = Clutter.get_default_backend().get_default_seat();
                    // seat.warp_pointer(x1, y1);
                    // //const vdevice = seat.create_virtual_device( Clutter.InputDeviceType.POINTER_DEVICE );
                    // //vdevice.notify_absolute_motion(global.get_current_time()+5, x1, y1);
                    // global.log('cxwins: pos 3a');
                }

                throw BreakException;
            } else {
                giter = giter + 1;
                if (giter >= gmax) {
                    giter = 0;
                }
                throw BreakException;
            }

        }

    }

});

// mw.activate(0);

} catch (e) {
    // global.log('cywins: giter', giter);
    eiter = giter.toString();
    // global.log('cywins: eiter', eiter);
    GLib.setenv('GITER', eiter, true);
    if (e !== BreakException) throw e;
}
"""

gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "$JS" >/dev/null

exit 0

