#!/bin/bash

if [[ -n "$WSL_DISTRO_NAME" || -n "$WSLENV" ]] ; then
    echo "wsl - noop ..."
    exit 0
fi

if [ $# -ge 1 ] ; then
  arg=$1
  if [ "$arg" != "1" -a "$arg" != "2" -a "$arg" != "3" ] ; then
    echo "invalid argument \"$arg\" (1-3)"
    exit
  fi
else
  arg=1
fi

# pagecache only, arg=1
# dentries and inodes, arg=2
# pagecache, dentries and inodes, arg=3

grep ^Cached /proc/meminfo
echo "sync; sync; echo $arg > /proc/sys/vm/drop_caches"
sudo sh -c "sync; sync; echo $arg > /proc/sys/vm/drop_caches"
grep ^Cached /proc/meminfo

# or
# sync; sync; sync; echo $arg | sudo tee /proc/sys/vm/drop_caches

