#!/bin/bash

if [[ $# -lt 2 ]] ; then
    echo "$(basename $0) : Error, need <file1> <file2> args ..."
    exit 1
fi

#command git diff --no-index $@

export FROM_GIT_LESS=1
git --no-pager diff --color=always $@ |& t2s -g |& less
