#!/bin/bash

unset BASH_ENV
shopt -u expand_aliases
unalias git

#echo "here: $INSIDE_GIT_WRAPPER"

if [[ -n "$INSIDE_GIT_WRAPPER" ]] ; then
    if [[ $1 == "diff" ]]; then
        shift
        command git dless "$@"
    elif [[ $1 == "log" ]]; then
        shift
        command git llog "$@"
    else
        command git "$@"
    fi
    exit 0
fi

trap "rm -f ~/.gitcmd-lock" EXIT SIGINT SIGTERM SIGQUIT

exec {lock_fd}>~/.gitcmd-lock || exit 1
flock "$lock_fd" || { echo "ERROR: flock() failed." >&2; exit 1; }

export INSIDE_GIT_WRAPPER=1

if [[ $1 == "diff" ]]; then
    shift
    command git dless "$@"
elif [[ $1 == "log" ]]; then
    shift
    command git llog "$@"
else
    command git "$@"
fi

