#!/bin/bash

trap "rm -f ~/.gitcmd-lock" EXIT SIGINT SIGTERM SIGQUIT

(
    flock 300
    if [[ $1 == "diff" ]]; then
        shift
        command git dless "$@"
    elif [[ $1 == "log" ]]; then
        shift
        command git llog "$@"
    else
        command git "$@"
    fi
) 300>~/.gitcmd-lock
