#!/bin/bash

gdir=""
gdir=$(git rev-parse --show-superproject-working-tree 2> /dev/null)
if [[ -z "${gdir}" ]]; then
    gdir=$(git rev-parse --show-toplevel 2> /dev/null)
fi
if [[ -z "$gdir" ]]
then
    echo "fatal: not a git repository (or any of the parent directories): .git"
    exit 1
fi

# if stdout is not a terminal its probably been redirected, so skip pager ...
if [ ! -t 1 ] ; then
    git --no-pager diff $1 $2 $3 $4
    exit
fi

# the +k was to go up one line and force a redraw at the top of the terminal ...
# use -c~ instead ...
# git --no-pager diff --color=always $1 $2 $3 $4 |& less -iR -K -x4 -c~
export FROM_GIT_LESS=1
git --no-pager diff --color=always $1 $2 $3 $4 |& smartless

