#!/bin/bash

unset BASH_ENV
shopt -u expand_aliases

# NOTE: there is also:
# git diff --name-only --diff-filter=d | xargs bat --diff

gdir=""
gdir=$(git rev-parse --show-superproject-working-tree 2> /dev/null)
if [[ -z "${gdir}" ]]; then
    gdir=$(git rev-parse --show-toplevel 2> /dev/null)
fi
if [[ -z "$gdir" ]]
then
    echo "fatal: not a git repository (or any of the parent directories): .git"
    exit 1
fi
git --no-pager diff $@ |& bat --style=plain

