#!/bin/bash

git() { $HOME/bin/git "$@"; }

gdir=""
gdir=$(git rev-parse --show-superproject-working-tree 2> /dev/null)
if [[ -z "${gdir}" ]]; then
    gdir=$(git rev-parse --show-toplevel 2> /dev/null)
fi
echo $gdir
