#!/bin/bash

git() { $HOME/bin/git "$@"; }

dbg=0

tfile1="/tmp/.git-status1$$.tmp"
tfile2="/tmp/.git-status2$$.tmp"
trap "rm -f $tfile1 $tfile2" EXIT SIGINT SIGTERM SIGQUIT

trap ':' HUP

# ----------

meth="dir"
git_dir="."
for arg in "$@"
do
  if [[ "${arg}" = "--use-tmux" ]] ; then
    # if calling this from byobu custom script, then
    # have that "5_gitinfo" script call this script
    # with a "--use-tmux" arg ...
    meth="tmux"
  else
    git_dir=${arg}
  fi
done

# TODO: maybe also check for TMUX env var ... ?

if [[ "${meth}" = "tmux" ]] ; then
  # get dir from current tmux window
  tmux_win=$(tmux list-windows | grep active | awk '{print $1}' | sed -e 's/://g')
  # strangely the -t<pane> is really a window index ...
  pcmd=$(tmux display-message -p -F "#{pane_current_command}" -t${tmux_win})
  # if pane command contains ssh substring then git dir is n/a ...
  if [[ -n "$pcmd" && $pcmd =~ ssh ]] ; then
    echo "git:<n/a>"
    exit 0
  fi
  git_dir=$(tmux display-message -p -F "#{pane_current_path}" -t${tmux_win})
  if [[ -z "${git_dir}" ]] ; then
    echo "git:<err(pane:null)>"
    exit 1
  fi
fi

# ----------

#echo "meth = ${meth}"
#echo "git_dir = ${git_dir}"

if [[ $dbg -ge 1 ]] ; then
  echo "pid: $$ meth: $meth dir: ${git_dir}" >> /tmp/dbg.$$
fi

cd ${git_dir} 2>/dev/null
rc=$?
if [[ $rc -ne 0 ]] ; then
  echo "git:<err(dir:${git_dir})>"
  if [[ $dbg -ge 1 ]] ; then
    echo "pid: $$ meth: $meth git:<err(dir:${git_dir})>" >> /tmp/dbg.$$
  fi
  exit 1
fi

# Much of this code is from git-prompt.sh from:
# Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# Distributed under the GNU General Public License, version 2.0.

repo_info="$(git rev-parse --git-dir --is-inside-git-dir \
    --is-bare-repository --is-inside-work-tree \
    --short HEAD 2>/dev/null)"
    
if [[ -z "$repo_info" ]] ; then
  echo "git:<n/a>"
  if [[ $dbg -ge 1 ]] ; then
    echo "pid: $$ meth: $meth git:<n/a>" >> /tmp/dbg.$$
  fi
  exit 0
fi

branch="$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')"

gs="git:<${branch}>"

let untracked_count=0 unstaged_count=0 staged_count=0 other_count=0

# skip .sw* files so current edit(s) do not show as untracked
git status --porcelain --branch | grep -v '\.sw*' > $tfile1 2>/dev/null

ab=""
grep -q '\[ahead ' $tfile1
rc=$?
if [[ $rc -eq 0 ]] ; then
  # ahead of origin
  ab="^"
fi
grep -q '\[behind ' $tfile1
rc=$?
if [[ $rc -eq 0 ]] ; then
  # behind of origin
  ab="${ab}-"
fi

tail -n +2 $tfile1 | cut -b -2 | sort -u > $tfile2 2>/dev/null
while IFS=_ read t; do
# echo "t = <$t>"
  if [[ "$t" = " M" ]] ; then
    ((unstaged_count++))
  elif [[ "$t" = "M " ]] ; then
    ((staged_count++))
  elif [[ "$t" = "??" ]] ; then
    ((untracked_count++))
  else
    ((other_count++))
  fi
done < $tfile2

rm -f $tfile1 $tfile2

stash=""
stash=$(git stash list 2>/dev/null)
if [[ -n "${stash}" ]] ; then
  ab="${ab}s"
fi

#echo "untracked_count(*) = $untracked_count"
#echo "unstaged_count(#)  = $unstaged_count"
#echo "staged_count(+)    = $staged_count"
#echo "other_count(o)     = $other_count"

if [[ $unstaged_count -gt 0 ]] ; then
  gs="${gs}*"
fi
if [[ $untracked_count -gt 0 ]] ; then
  gs="${gs}#"
fi
if [[ $staged_count -gt 0 ]] ; then
  gs="${gs}+"
fi
if [[ $other_count -gt 0 ]] ; then
  gs="${gs}o"
fi

gs="${gs}${ab}"

if [[ -n "$gs" ]] ; then
# window name has dir now, so skip dir in output
# ldir=$(echo ${git_dir} | awk -F/ '{print $NF}')
# echo ".../$ldir $gs"
  echo "$gs"
  if [[ $dbg -ge 1 ]] ; then
    echo "pid: $$ meth: $meth $gs" >> /tmp/dbg.$$
  fi
fi

exit 0
