#!/bin/bash

dbg=0

tfile="/tmp/git-status$$.tmp"
trap "rm -f $tfile" SIGINT SIGTERM SIGQUIT

if [ $# -gt 0 ] ; then
  # dir supplied on cmd-line
  active_tmux_dir=$1
  meth=dir
else
  # get dir from current tmux window
  active_tmux_win=$(tmux list-windows | grep active | awk '{print $1}' | sed -e 's/://g')
  # strangely the -t<pane> is really a window index ...
  active_tmux_dir=$(tmux display-message -p -F "#{pane_current_path}" -t${active_tmux_win})
  if [[ -z "${active_tmux_dir}" ]] ; then
    echo "git:<err(pane:null)>"
    exit 1
  fi
  meth=tmux
fi

if [[ $dbg -ge 1 ]] ; then
  echo "pid: $$ meth: $meth dir: ${active_tmux_dir}" >> /tmp/dbg.$$
fi

cd ${active_tmux_dir} 2>/dev/null
rc=$?
if [[ $rc -ne 0 ]] ; then
  echo "git:<err(dir:${active_tmux_dir})>"
  if [[ $dbg -ge 1 ]] ; then
    echo "pid: $$ meth: $meth git:<err(dir:${active_tmux_dir})>" >> /tmp/dbg.$$
  fi
  exit 1
fi

# Much of this code is from git-prompt.sh from:
# Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# Distributed under the GNU General Public License, version 2.0.

repo_info="$(git rev-parse --git-dir --is-inside-git-dir \
    --is-bare-repository --is-inside-work-tree \
    --short HEAD 2>/dev/null)"
    
if [[ -z "$repo_info" ]] ; then
  echo "git:<n/a>"
  if [[ $dbg -ge 1 ]] ; then
    echo "pid: $$ meth: $meth git:<n/a>" >> /tmp/dbg.$$
  fi
  exit 0
fi

branch="$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')"

gs="git:<${branch}>"

let untracked_count=0 unstaged_count=0 staged_count=0 other_count=0

# skip .sw* files so current edit(s) do not show as untracked
git status --porcelain | grep -v '\.sw*' | cut -b -2 | sort -u > $tfile 2>/dev/null

while IFS=_ read t; do
# echo "t = <$t>"
  if [[ "$t" = " M" ]] ; then
    ((unstaged_count++))
  elif [[ "$t" = "M " ]] ; then
    ((staged_count++))
  elif [[ "$t" = "??" ]] ; then
    ((untracked_count++))
  else
    ((other_count++))
  fi
done < $tfile

rm -f $tfile

#echo "untracked_count(*) = $untracked_count"
#echo "unstaged_count(#)  = $unstaged_count"
#echo "staged_count(+)    = $staged_count"
#echo "other_count(o)     = $other_count"

if [[ $unstaged_count -gt 0 ]] ; then
  gs="${gs}*"
fi
if [[ $untracked_count -gt 0 ]] ; then
  gs="${gs}#"
fi
if [[ $staged_count -gt 0 ]] ; then
  gs="${gs}+"
fi
if [[ $other_count -gt 0 ]] ; then
  gs="${gs}o"
fi

if [[ -n "$gs" ]] ; then
# window name has dir now, so skip dir in output
# ldir=$(echo ${active_tmux_dir} | awk -F/ '{print $NF}')
# echo ".../$ldir $gs"
  echo "$gs"
  if [[ $dbg -ge 1 ]] ; then
    echo "pid: $$ meth: $meth $gs" >> /tmp/dbg.$$
  fi
fi

exit 0
