#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
if [[ -z "$branch" ]] ; then
    echo "no git branch info found ..."
    exit 1
fi

git branch --set-upstream-to=origin/${branch} ${branch}

