#!/bin/bash

if [[ -z "$TMUX" ]]
then
    exit
fi

cmdline=`cat`

if [[ -z "$cmdline" ]]
then
    exit
fi

echo -n "$cmdline" | tmux load-buffer -

echo -n "$cmdline" | myclip

tmux display-message "copied cmdline to clipboard"


