#!/bin/bash

if command -v batcat > /dev/null; then
  BATNAME="batcat"
else
  BATNAME="bat"
fi

# $BATNAME --paging never --color always --style plain "$1"

if [[ -z "$BAT_STYLE" ]] ; then
    $BATNAME --paging=never --decorations=always --color=always --style=plain "$@"
else
    $BATNAME --paging=never --decorations=always --color=always "$@"
fi

