#!/bin/bash

if [[ $# -ge 1 ]] ; then
    HISTFILE=~/.zsh_hist.$1
else
    if [[ -z "$HISTFILE" ]]
    then
        HISTFILE=~/.zsh_hist.$PPID
    fi
fi

#echo "HISTFILE=$HISTFILE"

# skip if from sudo ...
if [[ -n "$SUDO_USER" && -n "$SUDO_UID" ]]
then
    exit 0
fi

myid=$(id -u)
if [[ $myid -eq 0 ]]
then
    exit 0
fi

if [[ -s $HISTFILE ]]
then
    owner=$(stat -c '%u' $HISTFILE)
    if [[ "$owner" != "$myid" ]]
    then
        exit 0
    fi
fi

trap "rm -f ~/.histfile-lock ; exit 0" EXIT SIGINT SIGTERM SIGQUIT

if [[ -s $HISTFILE ]]
then
    (
        flock 200
        touch ~/.mrghist
        chmod 600 ~/.mrghist
        cat $HISTFILE ~/.histfile | awk -v date="WILL_NOT_APPEAR$(date +"%s%N")" '{if (sub(/\\$/,date)) printf "%s", $0; else print $0}' | LC_ALL=C sort -u | awk -v date="WILL_NOT_APPEAR$(date +"%s%N")" '{gsub('date',"\\\n"); print $0}' | grep --text -v WILL_NOT_APPEAR | tail -n 5000 >> ~/.mrghist
        mv ~/.mrghist ~/.histfile
    ) 200>~/.histfile-lock
fi

