#!/bin/bash

if [[ $# -ge 1 ]] ; then
    HISTFILE=~/.zsh_hist.$1
else
    if [[ -z "$HISTFILE" ]]
    then
        HISTFILE=~/.zsh_hist.$PPID
    fi
fi

#echo "HISTFILE=$HISTFILE"

# skip if from sudo ...
if [[ -n "$SUDO_USER" && -n "$SUDO_UID" ]]
then
    exit 0
fi

myid=$(id -u)
if [[ $myid -eq 0 ]]
then
    exit 0
fi

if [[ -s $HISTFILE ]]
then
    owner=$(stat -c '%u' $HISTFILE)
    if [[ "$owner" != "$myid" ]]
    then
        exit 0
    fi
fi

trap "rm -f ~/.histfile-lock ; exit 0" EXIT SIGINT SIGTERM SIGQUIT

# strip trailing blanks and empty entries from history lines ...

if [[ -s $HISTFILE ]]
then
    (
        flock 200
        touch ~/.mrghist
        chmod 600 ~/.mrghist
        xvar=$(date +"%s%N")
        cat $HISTFILE ~/.histfile | grep -a -v ':0;$' 2>/dev/null | sed 's/ *$//g' 2>/dev/null | awk -v date="WILL_NOT_APPEAR$xvar" '{if (sub(/\\$/,date)) printf "%s", $0; else print $0}' | LC_ALL=C sort -u | awk -v date="WILL_NOT_APPEAR$xvar" '{gsub('date',"\\\n"); print $0}' | tail -n 10000 >> ~/.mrghist
        mv ~/.mrghist ~/.histfile
    ) 200>~/.histfile-lock
fi

