#!/bin/bash

nic=$(ip route 2>/dev/null | grep default | awk '{print $5}')

if [ -z "${nic}" ] ; then
  exit 1
fi

ip=$(ifconfig ${nic} 2> /dev/null | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')

if [ -z "${ip}" ] ; then
  exit 1
fi

echo ${ip}

exit 0

