#!/bin/bash

have_o=0
have_sc=0
have_rmnl=0
have_dash=0
have_text=0
sc_val=""
have_args=0
while [[ $# -ge 1 ]] ; do
    have_args=1
    if [[ $1 == '-o' || $1 == '--o' ]] ; then
        have_o=1
        shift
    elif [[ $1 == '-rmlastnl' || $1 == '--rmlastnl' ]] ; then
        have_o=1
        have_rmnl=1
        shift
    elif [[ $1 == '-sc' || $1 == '--sc' ]] ; then
        shift
        if [[ $# -ge 1 ]] ; then
            have_o=1
            have_sc=1
            sc_val=$1
            shift
        else
            echo "Error, -sc arg requires value [-1,0,1] or file"
            exit 1
        fi
    elif [[ $1 == '-' ]] ; then
        have_dash=1
        shift
    else
        have_text=1
        escapedtext=$(printf %q "$@")
        shift
    fi
done

# ===================================


if [[ $have_args -eq 0 || $have_dash -eq 1 ]] ; then
    #exec xsel -i -p
    exec copyq >/dev/null 2>/dev/null "copy(input()); copySelection(input())"
elif [[ $have_text -eq 1 ]] ; then
    #echo "$escapedtext" | xsel -i -p
    echo "$escapedtext" | copyq >/dev/null 2>/dev/null "copy(input()); copySelection(input())"
    exit 0
fi

# ===================================

add=0
if [[ $have_sc -eq 1 ]] ; then
    if [[ $sc_val == "-1" ]] ; then
        add=$sc_val
    elif [[ $sc_val == "0" ]] ; then
        add=$sc_val
    elif [[ $sc_val  == "1" ]] ; then
        add=$sc_val
    else
        # if not -1, 0, 1 then some path with / in it ...
        if [[ "$sc_val" == *\/* ]] ; then
            if [[ ! -s $sc_val ]] ; then
                add=1
            else
                add=$(cat $sc_val | tr -d '\n')
            fi
        else
            echo "Error, -sc arg requires value [-1,0,1] or file"
            exit 1
        fi
    fi
fi

pre=""
pos=""
if [[ ${add} -eq -1 ]] ; then
    pre=" "
elif [[ ${add} -eq 1 ]] ; then
    pos=" "
fi

echo -n "$pre"

if [[ $have_rmnl -eq 0 ]] ; then
    copyq clipboard
else
    copyq clipboard | sed -z '$s/\n$//'
fi

echo -n "$pos"

exit 0
