#!/bin/bash

# skip if starting a vim/nvim terminal ...

if [[ -n "$VIM_TERMINAL" || -n "$NVIM_LOG_FILE" ]] ; then
    exit 0
fi

if [[ $# -ge 1 ]] ; then
    title="$1"
else
    title="mlterm"
fi

# seems to only work inside tmux ...

if [[ -n "$TMUX_PANE" ]] ; then
    printf "\033Ptmux;\033\033]0;${title}\007\033\\"
else
    printf "\033]0;${title}\007"
fi

