#!/bin/bash

if [[ $# == 1 ]] ; then
    rm -f ~/.zsh_hist.$$
    exec $0
fi

export BYOBU_CONFIG_DIR=~/.byobu

PKG="byobu"

# Create and export the runtime cache directory
if [ -w /dev/shm ]; then
	# Use shm for performance, if possible
	for i in /dev/shm/$PKG-$USER-*; do
		if [ -d "$i" ] && [ -O "$i" ]; then
			export BYOBU_RUN_DIR="$i"
			break
		fi
	done
	# Still empty, make a new one
	if [ ! -d "$BYOBU_RUN_DIR" ] || [ ! -O "$BYOBU_RUN_DIR" ]; then
		export BYOBU_RUN_DIR=$(mktemp -d /dev/shm/$PKG-$USER-XXXXXXXX)
	fi
fi
if [ ! -d "$BYOBU_RUN_DIR" ] || [ ! -O "$BYOBU_RUN_DIR" ] || [ ! -w "$BYOBU_RUN_DIR" ]; then
	# For distros that don't have a /dev/shm, use local disk
	if [ -d "$XDG_CACHE_HOME" ]; then
		# Use XDG, as some users insist on such nonsense :-)
		export BYOBU_RUN_DIR="$XDG_CACHE_HOME/$PKG"
	else
		# But if not, we'll use a cache directory
		export BYOBU_RUN_DIR="$HOME/.cache/$PKG"
	fi
fi

exec tmux -u -2 -f $BYOBU_CONFIG_DIR/tmuxrc

