#!/bin/bash

zuttypid=$(pgrep zutty)

if [[ -z "${zuttypid}" ]] ; then
    echo "no zutty pid" >> /tmp/zutty.log
    exit 1
fi

sleep 1.5

winid=$(wmctrl -lp | grep "${zuttypid}" | awk '{print $1}')

if [[ -z "${winid}" ]] ; then
    sleep 1.5
    winid=$(wmctrl -lp | grep "${zuttypid}" | awk '{print $1}')
    if [[ -z "${winid}" ]] ; then
        echo "no zutty wmctrl id" >> /tmp/zutty.log
        exit 1
    fi
fi

#echo "wmctrl id = ${winid}" >> /tmp/zutty.log

wmctrl -i -r ${winid} -e 0,690,678,2530,1350

exec $SHELL

