#!/bin/bash

if [[ -z "$TMUX" ]]
then
    exit
fi

if [[ $# -ne 2 ]]
then
    exit
fi

trap "rm -f /tmp/.ex /tmp/.ey" SIGINT SIGQUIT SIGTERM

ox=$1
oy=$2

tmux send-keys C-a
tmux send-keys C-e
tmux run "echo #{cursor_x} > /tmp/.ex"
ex=$(cat /tmp/.ex)
rm -f /tmp/.ex
tmux run "echo #{cursor_y} > /tmp/.ey"
ey=$(cat /tmp/.ey)
rm -f /tmp/.ey
ex=$((ex-1))

tmux send-keys C-a
tmux run "echo #{cursor_x} > /tmp/.ex"
bx=$(cat /tmp/.ex)
rm -f /tmp/.ex
tmux run "echo #{cursor_y} > /tmp/.ey"
by=$(cat /tmp/.ey)
rm -f /tmp/.ey

num_lines=$((ey-by))

#echo "ex = $ex"
#echo "ey = $ey"
#echo "bx = $bx"
#echo "by = $by"

#echo "num_lines = $num_lines"

if [[ $num_lines -eq 0 ]]
then
    num_cols=$((ex-bx))
    if [[ $num_cols -lt 0 ]]
    then
        exit 0
    fi
fi

#prev_mode=$(tmux run "echo #{mode-style}")
#tmux set -g mode-style "bg=default,fg=default"
pane_changed_hook=$(tmux show-hooks -gw pane-mode-changed | awk '{for (i=2; i<=NF; i++) printf " "$i}')
if [[ -n "$pane_changed_hook" ]]
then
    tmux set-hook -g pane-mode-changed ""
fi

tmux copy-mode -H
tmux send-keys v

if [[ $num_lines -eq 0 ]]
then
    num_cols=$((ex-bx))
    tmux send-keys -XN $num_cols cursor-right
    tmux send-keys -X copy-pipe-and-cancel "tmux wait -S pipe"
    tmux wait pipe
    tmux set-buffer -n cmdx
    tmux show-buffer -b cmdx | tr -d '\n' | myclip -
    tmux delete-buffer -b cmdx

    #tmux set -g mode-style "$prev_mode"
    if [[ -n "$pane_changed_hook" ]]
    then
        tmux set-hook -g pane-mode-changed "$pane_changed_hook"
    fi

    tmux send -X cancel
    # TODO: MCK - back to orig oy ...
    #num_cols=$((ox-bx))
    #tmux send-keys -N $num_cols Right
    tmux send-keys C-e

    tmux display-message "copied cmdlne to clipboard"

    exit 0
fi

# multi-line ...

o_lines=$((oy-by))

tx=0
l=0
while [[ $l -le $num_lines ]]
do
    if [[ $l -eq $num_lines ]]
    then
        num_cols=$ex
        tmux send-keys -X end-of-line
        tmux send-keys -X copy-pipe-and-cancel "tmux wait -S pipe"
        tmux wait pipe
        tmux set-buffer -n cmdx
        tmux show-buffer -b cmdx | tr -d '\n' | myclip -
        tmux delete-buffer -b cmdx

        #tmux set -g mode-style "$prev_mode"
        if [[ -n "$pane_changed_hook" ]]
        then
            tmux set-hook -g pane-mode-changed "$pane_changed_hook"
        fi

        tmux send -X cancel
        # TODO: MCK - back to orig ox, oy ...
        #tx=$((tx+ox))
        #tmux send-keys -N $tx Right
        #echo "tx = $tx"
        tmux send-keys C-e

        tmux display-message "copied cmdlne to clipboard"

        exit 0
    else
        tmux run "echo #{copy_cursor_x} > /tmp/.ex"
        px=$(cat /tmp/.ex)
        rm -f /tmp/.ex
        tmux run "echo #{copy_cursor_y} > /tmp/.ey"
        py=$(cat /tmp/.ey)
        rm -f /tmp/.ey

        tmux send-keys -X end-of-line

        tmux run "echo #{copy_cursor_x} > /tmp/.ex"
        mx=$(cat /tmp/.ex)
        rm -f /tmp/.ex
        dx=$((mx-px))
        tx=$((tx+mx))
        tmux send-keys -X cursor-down
        tmux send-keys -X cursor-right
    fi
    l=$((l+1))
done

#tmux set -g mode-style "$prev_mode"
exit 0

