#!/bin/bash

if [[ $# -lt 1 ]] ; then
    echo "Error: no cmd provided ..."
    exit 22
fi

if [[ -n "$TMUX_PANE" ]] ; then
    #tmux popup -d '#{pane_current_path}' -E "bash_ask $*"
    tmux popup -d '#{pane_current_path}' -E "tmux new -s popup \"printf \\\"\033]11;rgb:30/30/30\007\\\" ; tmux set -w status off ; bash_ask $*\""
else
    echo "Error: TMUX not running ..."
    exit 22
fi

