#!/bin/bash 

if [ $# -eq 0 ] ; then
  echo "Error, missing 0|1 arg"
  exit
fi

arg=$1

# for some unknown reason changing the Synaptics setting reverts other changes, so skip it
list=$(xinput list | grep -i 'Touchpad' | grep -v Synaptics | awk -F= '{ print $2}' | awk '{print $1}')

while read -r item
do
  if [[ -n "${item}" ]] ; then
    #echo "xinput set-prop $item \"Device Enabled\" $arg"
    if [[ "$arg" == "0" ]] ; then
        notify-send -t 2000 "laptop touchpad disabled ..."
    else
        notify-send -t 2000 "laptop touchpad enabled ..."
    fi
    xinput set-prop ${item} "Device Enabled" ${arg}
  fi
done <<< "$list"

# older method that doesnt seem to work
#if [[ ${arg} == "0" ]] ; then
#    synclient TouchpadOff=1
#else
#    synclient TouchpadOff=0
#fi
