#!/bin/bash

#if [[ -n "$FLOATERM" ]] ; then
#    floaterm "$@"
#fi

re1='/vim/'
re2='/nvim/'

if [[ -n $VIMRUNTIME ]] ; then
    if [[ $VIMRUNTIME =~ $re1 ]] ; then
        exec vim $@
    elif [[ $VIMRUNTIME =~ $re2 ]] ; then
        exec nvim $@
    fi
fi

if [[ -n "$TMUX" ]] ; then
    if [[ -z "$VISUAL" ]] ; then
        #unset TMUX
        exec nvim "$@"
    elif [[ "$VISUAL" != "vim" ]] ; then
        #unset TMUX
        exec nvim "$@"
    else
        exec vim "$@"
    fi
else
    if [[ -z "$VISUAL" ]] ; then
        exec nvim "$@"
    elif [[ "$VISUAL" != "vim" ]] ; then
        exec nvim "$@"
    else
        exec vim "$@"
    fi
fi
