#!/bin/bash

if [[ -n "$TMUX" ]] ; then
    if [[ -z "$VISUAL" ]] ; then
        TMUX= exec nvim $@
    elif [[ "$VISUAL" == "vim" ]] ; then
        exec vim $@
    else
        TMUX= exec nvim $@
    fi
else
    if [[ -z "$VISUAL" ]] ; then
        exec nvim $@
    elif [[ "$VISUAL" == "vim" ]] ; then
        exec vim $@
    else
        exec nvim $@
    fi
fi
