#!/bin/bash

if [[ -n "$TMUX" ]] ; then
    if [[ -z "$VISUAL" ]] ; then
        unset TMUX
        exec nvim -R "$@"
    elif [[ "$VISUAL" != "vim" ]] ; then
        unset TMUX
        exec nvim -R "$@"
    else
        exec vim -R "$@"
    fi
else
    if [[ -z "$VISUAL" ]] ; then
        exec nvim -R "$@"
    elif [[ "$VISUAL" != "vim" ]] ; then
        exec nvim -R "$@"
    else
        exec vim -R "$@"
    fi
fi
