#!/bin/bash

if [[ -z "$VLESS" ]] ; then
    if [[ -z "$VISUAL" ]] ; then
        exec nvimless $@
    elif [[ "$VISUAL" == "vim" ]] ; then
        exec vimless $@
    else
        exec nvimless $@
    fi
elif [[ "$VLESS" == "vless" ]] ; then
    exec vimless $@
else
    exec nvimless $@
fi
