#!/bin/sh
# Shell script to start Vim with less.vim.
# Read stdin if no arguments were given and stdin was redirected.

if test -t 1; then
  if test $# = 0; then
    if test -t 0; then
      echo "Missing filename" 1>&2
      exit
    fi
    vim --cmd 'let no_plugin_maps = 1' --cmd 'set rtp^=$HOME/.vim/vless' -c 'runtime! vless.vim' -c ':nnoremap v <Nop>' -c ':set mouse-=a' -c ':ColorHighlight!' -
  else
    vim --cmd 'let no_plugin_maps = 1' --cmd 'set rtp^=$HOME/.vim/vless' -c 'runtime! vless.vim' -c ':nnoremap v <Nop>' -c ':set mouse-=a' -c ':ColorHighlight!' "$@"
  fi
else
  # Output is not a terminal, cat arguments or stdin
  if test $# = 0; then
    if test -t 0; then
      echo "Missing filename" 1>&2
      exit
    fi
    cat
  else
    cat "$@"
  fi
fi
