#!/bin/bash

if [[ -z "$VLESS" ]] ; then
    if [[ -z "$VISUAL" ]] ; then
        vimless $@
    elif [[ "$VISUAL" == "vim" ]] ; then
        vimless $@
    else
        nvimless $@
    fi
elif [[ "$VLESS" == "vless" ]] ; then
    vimless $@
else
    nvimless $@
fi
