#!/bin/bash

# /lib/systemd/system-sleep/post
# run script at resume|thaw (post)

USERID=<user>
SCRIPT="/home/<user>/bin/xmodmap.fix"

case "$1" in
  pre)
     ;;
  post)
    export DISPLAY=":0"
    export XAUTHORITY="/home/$USERID/.Xauthority"
    su $USERID -c "$SCRIPT"
     ;;
  *) exit $NA
     ;;  
esac

