reporting: "off"
startuppopupversion: 1
os:
    editPreset: 'nvim'
keybinding:
    files:
        openStatusFilter: '<f1>'
    universal:
        quit: '<f12>'
        return: '<esc>'
        redo: '<c-6>'
        undo: '<c-8>'
        scrollUpMain-alt1: '<c-b>' # main panel scrool up
        scrollDownMain-alt1: '<c-f>' # main panel scrool down
        scrollUpMain-alt2: '<c-k>'
        scrollDownMain-alt2: '<c-j>'
