reporting: "off"
startuppopupversion: 1
keybinding:
    universal:
        quit: '<f12>'
        return: '<c-q>'
        scrollUpMain-alt1: '<c-b>' # main panel scrool up
        scrollDownMain-alt1: '<c-f>' # main panel scrool down
